# Generated by Django 2.2.7 on 2019-11-29 13:47

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('comments', 'Comment')
    Student(name="Joe Silver", relationship="joeemail.com", comment="22342342").save()

class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_data),
    ]
