# Generated by Django 3.0.8 on 2020-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=240, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='relationship',
            field=models.CharField(max_length=240, verbose_name='Relationship'),
        ),
    ]
